### ISSUE TITLE
application-path is needed for rest api? (gradle)

### ISSUE THREAD

**Issue by StephenOTT** [holunda-io/camunda-springboot-kotlin#1]
Hey

i built a gradle equiv of this project and I seem to require the following in the application.yml for the rest api to work:

```yml
spring:
  jersey:
    application-path: /rest
```

any ideas why?
